import os
from dotenv import load_dotenv

load_dotenv()

LOAD_MODE = os.getenv('LOAD_MODE')
FIT_FLG = eval(os.getenv('FIT_FLG'))

VECTORIZER_PATH = os.getenv('VECTORIZER_PATH')

NB_PIPELINE_QUEUE_PATH = os.getenv('NB_PIPELINE_QUEUE_PATH')
NB_PIPELINE_PRIORITY_PATH = os.getenv('NB_PIPELINE_PRIORITY_PATH')

NB_MODEL_QUEUE_PATH = os.getenv('NB_MODEL_QUEUE_PATH')
NB_MODEL_PRIORITY_PATH = os.getenv('NB_MODEL_PRIORITY_PATH')

LR_PIPELINE_QUEUE_PATH = os.getenv('LR_PIPELINE_QUEUE_PATH')
LR_PIPELINE_PRIORITY_PATH = os.getenv('LR_PIPELINE_PRIORITY_PATH')

LR_MODEL_QUEUE_PATH = os.getenv('LR_MODEL_QUEUE_PATH')
LR_MODEL_PRIORITY_PATH = os.getenv('LR_MODEL_PRIORITY_PATH')

BERT_PIPELINE_QUEUE_PATH = os.getenv('BERT_PIPELINE_QUEUE_PATH')
BERT_PIPELINE_PRIORITY_PATH = os.getenv('BERT_PIPELINE_PRIORITY_PATH')

BERT_MODEL_QUEUE_PATH = os.getenv('BERT_MODEL_QUEUE_PATH')
BERT_MODEL_PRIORITY_PATH = os.getenv('BERT_MODEL_PRIORITY_PATH')

DISTILBERT_PIPELINE_QUEUE_PATH = os.getenv('DISTILBERT_PIPELINE_QUEUE_PATH')
DISTILBERT_PIPELINE_PRIORITY_PATH = os.getenv('DISTILBERT_PIPELINE_PRIORITY_PATH')

DISTILBERT_MODEL_QUEUE_PATH = os.getenv('DISTILBERT_MODEL_QUEUE_PATH')
DISTILBERT_MODEL_PRIORITY_PATH = os.getenv('DISTILBERT_MODEL_PRIORITY_PATH')